spring:
  task:
    scheduling:
      pool:
        size: 10

  datasource:
    url: jdbc:postgresql://localhost:6432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    initialization-mode: always
    hikari:
      maximumPoolSize: 50

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: cases
        jdbc:
          lob:
            non_contextual_creation: true



  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 6672
    virtualhost: /

queueconfig:
  inbound-queue: case.sample.inbound
  outbound-exchange: outbound-exchange
  outbound-routing-key: demo-routing-key-out
  print-queue: caseProcessor.printFileSvc.printBatchRow
  consumers: 50

logging:
  level:
    org.springframework.amqp.rabbit.listener.ConditionalRejectingErrorHandler: INFO

scheduler:
  frequency: 1000 #milliseconds
  chunksize: 1000
