version: "3.4"
services:
  demo-java-processor:
    container_name: demo-java-processor
    image: eu.gcr.io/census-rm-ci/rm/demo-java-processor
    external_links:
      - postgres-ref
      - rabbitmq-ref
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-ref:${POSTGRES_PORT}/${POSTGRES_HOST}?sslmode=disable
      - SPRING_RABBITMQ_HOST=${RABBIT_HOST}
      - SPRING_RABBITMQ_PORT=${RABBIT_PORT}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - censusrmdockerdev_reference

  demo-printfilesvc:
    container_name: demo-printfilesvc
    image: eu.gcr.io/census-rm-ci/rm/demo-print-file-service
    external_links:
      - rabbitmq
      - sftp
    environment:
      - RABBIT_QUEUE=caseProcessor.printFileSvc.printBatchRow
      - RABBIT_HOST=${RABBIT_HOST}
      - RABBIT_PORT=${RABBIT_PORT}
      - RABBIT_USERNAME=guest
      - RABBIT_PASSWORD=guest
      - RABBIT_VIRTUALHOST=/
      - READINESS_FILE_PATH=/tmp/ready
      - ENVIRONMENT=DEV
      - SFTP_HOST=sftp
      - SFTP_PORT=22
      - SFTP_USERNAME=centos
      - SFTP_KEY_FILENAME=/home/printfile/dummy_keys/dummy_rsa
      - SFTP_PASSPHRASE=dummy_secret
      - EXCEPTIONMANAGER_CONNECTION_HOST=${EXCEPTIONMANAGER_HOST}
      - EXCEPTIONMANAGER_CONNECTION_PORT=${EXCEPTIONMANAGER_PORT}
      - SUPPLIER_CONFIG_JSON_PATH=/home/printfile/dummy_supplier_config.json
      - SUPPLIER_KEY_DIRECTORY=/home/printfile/dummy_keys
    restart: always
    healthcheck:
      test: sh -c "[ -f /tmp/ready ]"
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 50s
    volumes:
      - ./dummy_keys:/home/printfile/dummy_keys
      - ./dummy_supplier_config.json:/home/printfile/dummy_supplier_config.json

networks:
  default:
    external:
      name: censusrmdockerdev_reference